### PR TITLE
PLT-9415: Unit testing setup

### PR DESCRIPTION
**Pull request by EehMauro**
@coderabbitai: ignore

## Summary by CodeRabbit

- **New Features**
	- Added polyfills for compatibility with Node.js environments.
	- Introduced a function to facilitate rendering React components for testing.
	- Added export of `AppStore` type for the store object.
- **Enhancements**
	- Updated the CI workflow to execute tests more efficiently.
	- Enhanced test configurations for better mapping and environment setup.
	- Improved accessibility by adding `role="button"` to the Button component.
- **Bug Fixes**
	- Fixed import paths for the `fetch` function across various slices to reflect the new file structure accurately.
- **Tests**
	- Added new test suites for `ConnectSection` and `SubscriptionSection` components, including modal behavior and subscription tier interaction.

### CODE REVIEW

**Comment by KJES4** [comment]
1. The module imports for RTL in this file `test-utils.tsx` can be imported in one line `import { render, RenderOptions } from '@testing-library/react';`
2. The react imports are never read in the test files so this import doesn’t need to be included in these files.
3. Maybe we don't want to use `getTestID` in `ConnectSection.test.tsx`? We should probably use a semantic query to mirror the way users will interact with the application.
4. Since the assertions in the test block in `SubscriptionSection.test.tsx` are testing two different things in the same component it would be good to separate them into two tests inside a describe block.

**Comment by EehMauro** [comment]
> 1. The module imports for RTL in this file `test-utils.tsx` can be imported in one line `import { render, RenderOptions } from '@testing-library/react';`
> 2. The react imports are never read in the test files so this import doesn’t need to be included in these files.
> 3. Maybe we don't want to use `getTestID` in `ConnectSection.test.tsx`? We should probably use a semantic query to mirror the way users will interact with the application.
> 4. Since the assertions in the test block in `SubscriptionSection.test.tsx` are testing two different things in the same component it would be good to separate them into two tests inside a describe block.

Resolved!

**Review by KJES4 — APPROVED** [review]
Looks good.

**Review by amnambiar — APPROVED** [review]
Looks good! :+1:

**Pull request merged**
